/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frogger;

import java.io.*;
import java.awt.Color;
import java.applet.AudioClip;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelos.Enemigo;
import modelos.Jugador;
import modelos.bg;
import modelos.vida;

/**
 *
 * @author diegoalejandromarulandamarin
 */
public final class dibujo extends javax.swing.JPanel {
    
    AudioClip sonido;
    AudioClip muerte;
    String jugador;
    String FILENAME = "/Users/diegoalejandromarulandamarin/Desktop/Prog 2/frogger/src/puntajes/puntajes.txt";
    Jugador J1;
    bg fondo;
    int puntos = 0;
    int animaciones;
    int count = 0;
    int puntajeactual;
    ArrayList<vida> corazones;
    ArrayList<Enemigo> enemigos;
    int vidas = -1;
    public int getPuntos(){
        return puntos;
    }
    public void setPuntos(int puntos){
        this.puntos = puntos;
    }
    public vida crearcorazon(int x, int y, int ancho, int alto){
        vida corazon = new vida(x,y,ancho,alto);
        return corazon;
    }
    
    public Enemigo createEnemy(int x, int y, int width, int heigth,boolean orientation, boolean isCarro) {
        Enemigo enemigo = new Enemigo(x,y,width, heigth, orientation, isCarro);
        return enemigo;
    }
    public dibujo() {
        this.sonido = java.applet.Applet.newAudioClip(getClass().getResource("../sonido/fondo.wav"));
        this.muerte = java.applet.Applet.newAudioClip(getClass().getResource("../sonido/muerte.wav"));
        initComponents();
        corazones = new ArrayList();
        corazones.add(crearcorazon(395,0,34,30));
        corazones.add(crearcorazon(430,0,34,30));
        corazones.add(crearcorazon(465,0,34,30));
              
        this.J1 = new Jugador(219, 510);
                        
        enemigos = new ArrayList();
        
        enemigos.add(createEnemy(499,70,60,40,false,false));
        enemigos.add(createEnemy(139,70,60,40,false,false));
        
        enemigos.add(createEnemy(119,130,60,40,true,false));
        enemigos.add(createEnemy(360,130,60,40,true,false));
        
        enemigos.add(createEnemy(159,190,60,40,false,false));
        enemigos.add(createEnemy(400,190,60,40,false,false));
        
        enemigos.add(createEnemy(219, 315, 60, 40, true, true));
        enemigos.add(createEnemy(0, 315, 60, 40, true, true));
        
        enemigos.add(createEnemy(0, 380, 60, 40, false, true));
        enemigos.add(createEnemy(325, 380, 60, 40, false, true));
        
        enemigos.add(createEnemy(100, 450, 60, 40, true, true));
        enemigos.add(createEnemy(399, 450, 60, 40, true, true));
        animaciones = 0;
        sonido.loop();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.        
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void Direcciones(int D) {

        if (J1 != null) {

            if (this.animaciones == 2) {
                this.animaciones = 0;
            }

            switch (D) {
                case 1:
                    this.J1.setDibujo(new ImageIcon(getClass().getResource(this.J1.getRutasar()[animaciones])));
                    this.J1.setY(this.J1.getY() - 60);
                    animaciones++;
                    repaint();
                    this.J1.setDibujo(new ImageIcon(getClass().getResource(this.J1.getRutasar()[animaciones])));                                
                    break;
                case 2:
                    this.J1.setDibujo(new ImageIcon(getClass().getResource(this.J1.getRutasab()[animaciones])));
                    this.J1.setY(this.J1.getY() + 60);
                    animaciones++;
                    break;
                case 3:
                    this.J1.setDibujo(new ImageIcon(getClass().getResource(this.J1.getRutasiz()[animaciones])));
                    this.J1.setX(this.J1.getX() - 60);
                    animaciones++;
                    break;
                case 4:
                    this.J1.setDibujo(new ImageIcon(getClass().getResource(this.J1.getRutasde()[animaciones])));
                    this.J1.setX(this.J1.getX() + 60);
                    animaciones++;
                    break;
                default:
                    break;
            }

            if (this.J1.getX() > 500) {
                this.J1.setX(0);
            }

            if (this.J1.getX() < 0) {
                this.J1.setX(500);
            }

            if (this.J1.getY() <= 47) {
                puntos+= 100;
                this.J1.setX(219);
                this.J1.setY(520);
                //for (int i = 0; i < troncos.size(); i++) {
                    //this.troncos.get(i).setVelocidad((float) (this.troncos.get(i).getVelocidad() + 0.1f));
                //}
                //for (int j = 0; j < carros.size(); j++) {
                    //this.carros.get(j).setVelocidad((float) (this.carros.get(j).getVelocidad() + 0.1f));
                //}
            }

            if (this.J1.getY() > 500) {
                this.J1.setY(500);
            }

        }
    }
    
    public void Colisiones(Graphics g) {
        if (count == 0) {
            for (int i = 0; i < enemigos.size(); i++) {
                if (J1.getColision().intersects(enemigos.get(i).getColision())){                      
                    count++;
                    if (vidas != 2) {
                        vidas+= 1;
                        this.J1.setX(219);
                        this.J1.setY(510);
                        this.corazones.get(vidas).setVida(this.corazones.get(vidas).getVidaper());
                        count = 0;
                    }
                    else{
                    J1.setDibujo(J1.getDibujom());
                    repaint();
                    this.enemigos.get(i).setBandera(false);
                    for (int j = 0; j < enemigos.size(); j++) {
                        this.enemigos.get(j).setBandera(false);
                    }
                    sonido.stop();
                    muerte.play();                    
                    BufferedWriter bw = null;
                    FileWriter fw = null;
                    
                    try (BufferedReader br = new BufferedReader(new FileReader(FILENAME))) {

			String sCurrentLine;

			while ((sCurrentLine = br.readLine()) != null) {
                            puntajeactual = Integer.parseInt(sCurrentLine);
			}

                    }catch (IOException e) {
			e.printStackTrace();
                    }
                    if (puntajeactual < puntos) {                                                                    
                        try {
                            String marcador = Integer.toString(puntos);
                            fw = new FileWriter(FILENAME);
                            bw = new BufferedWriter(fw);
                            bw.write(marcador);
                        }catch (IOException e) {
                            e.printStackTrace();
                        }finally {
                            try {
                                if (bw != null)
                                    bw.close();
                                if (fw != null)
                                    fw.close();
                            }
                            catch (IOException ex) {
                                ex.printStackTrace();
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Gracias por jugar");
                    System.exit(0);
                    }  
                }
            }
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        fondo= new bg();        
        
        g.drawImage(this.fondo.getfondoso().getImage(), 0, 0, 500, 559, this);        
        
        for (int k = 0; k < corazones.size(); k++) {
            g.drawImage(this.corazones.get(k).getVida().getImage(), this.corazones.get(k).getX(), this.corazones.get(k).getY(), this.corazones.get(k).getAncho(), this.corazones.get(k).getAlto(), this);
        }              
        
        for (int i = 0; i < enemigos.size(); i++) {
            g.drawImage(this.enemigos.get(i).getDibujo().getImage(), (int)this.enemigos.get(i).getX(), this.enemigos.get(i).getY(), this.enemigos.get(i).getAncho(), this.enemigos.get(i).getAlto(), this);
        }
       
        if (this.J1 != null) {
            g.drawImage(this.J1.getDibujo().getImage(), this.J1.getX(), this.J1.getY(), this.J1.getAncho(), this.J1.getAlto(), this);
            Colisiones(g);
        }
        g.setColor(Color.white);
        g.setFont(new Font("Silom", Font.BOLD,28));
        g.drawString("Puntos: " + puntos, 5, 540);
        
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
